export const ROLES = [
  {
    name: 'admin',
    permissions: [
      'viewRoles',
      'modifyRoles',
      'modifyUsers',
      'viewUsers',
      'viewManagementSquad',
      'modifyManagementSquad',
      'viewManagementSquadInfo',
      'modifyManagementSquadInfo',
      'viewEvents',
      'modifyEvents',
      'viewAnnouncements',
      'modifyAnnouncements',
      'viewNews',
      'modifyNews',
      'viewDocuments',
      'modifyDocuments',
      'viewImages',
      'modifyImages',
      'viewEducation',
      'modifyEducation',
      'viewReport',
      'generateReport',
    ],
    city: '*',
    district: '*',
  },

  {
    name: 'genel-merkez-admin',
    permissions: [
      'modifyUsers',
      'viewUsers',
      'viewManagementSquad',
      'modifyManagementSquad',
      'viewManagementSquadInfo',
      'modifyManagementSquadInfo',
      'viewEvents',
      'modifyEvents',
      'viewAnnouncements',
      'modifyAnnouncements',
      'viewNews',
      'modifyNews',
      'viewDocuments',
      'modifyDocuments',
      'viewImages',
      'modifyImages',
      'viewEducation',
      'modifyEducation',
      'viewReport',
      'generateReport',
    ],
    city: '*',
    district: '*',
  },

  {
    name: 'genel-merkez-goruntuleme',
    permissions: [
      'viewUsers',
      'viewManagementSquad',
      'viewManagementSquadInfo',
      'viewEvents',
      'viewAnnouncements',
      'viewNews',
      'viewDocuments',
      'viewImages',
      'viewEducation',
      'viewReport',
    ],
    city: '*',
    district: '*',
  },

  {
    name: 'il-icra-admin',
    permissions: [
      'modifyUsers',
      'viewUsers',
      'viewManagementSquad',
      'modifyManagementSquad',
      'viewManagementSquadInfo',
      'modifyManagementSquadInfo',
      'viewEvents',
      'modifyEvents',
      'viewAnnouncements',
      'modifyAnnouncements',
      'viewNews',
      'modifyNews',
      'viewDocuments',
      'modifyDocuments',
      'viewImages',
      'modifyImages',
      'viewEducation',
      'modifyEducation',
      'viewReport',
      'generateReport',
    ],
    city: '*',
    district: '*',
  },

  {
    name: 'il-icra-goruntuleme',
    permissions: [
      'viewUsers',
      'viewManagementSquad',
      'viewManagementSquadInfo',
      'viewEvents',
      'viewAnnouncements',
      'viewNews',
      'viewDocuments',
      'viewImages',
      'viewEducation',
      'viewReport',
    ],
    city: '*',
    district: '*',
  },

  {
    name: 'ilce-icra-admin',
    permissions: [
      'modifyUsers',
      'viewUsers',
      'viewManagementSquad',
      'modifyManagementSquad',
      'viewManagementSquadInfo',
      'modifyManagementSquadInfo',
      'viewEvents',
      'modifyEvents',
      'viewAnnouncements',
      'modifyAnnouncements',
      'viewNews',
      'modifyNews',
      'viewDocuments',
      'modifyDocuments',
      'viewImages',
      'modifyImages',
      'viewEducation',
      'modifyEducation',
      'viewReport',
      'generateReport',
    ],
    city: '*',
    district: '*',
  },

  {
    name: 'ilce-icra-goruntuleme',
    permissions: [
      'viewUsers',
      'viewManagementSquad',
      'viewManagementSquadInfo',
      'viewEvents',
      'viewAnnouncements',
      'viewNews',
      'viewDocuments',
      'viewImages',
      'viewEducation',
      'viewReport',
    ],
    city: '*',
    district: '*',
  },
];
